services:
  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: 'rabbitmq_api_client'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:17
    container_name: vism_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vism
      POSTGRES_PASSWORD: vism
      POSTGRES_DB: vism
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vism -d vism"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres2:
    image: postgres:17
    container_name: vism_acme_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vism_acme
      POSTGRES_PASSWORD: vism_acme
      POSTGRES_DB: vism_acme
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vism -d vism"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  postgres_data2:
    driver: local